### ISSUE TITLE
Formatting RFC3339

### ISSUE THREAD

**Issue by morilog** [yaa110/go-persian-calendar#12]
The main time package when timezone is UTC formats the date in RFC3339 like this:
`2019-10-10T10:20:33Z`
and for example for Tehran timezone formats like this:
`2019-10-10T10:20:33+03:30`

But your package for UTC acts as other timezones and formats as 
`1398-08-15T10:20:22+00:00`

I think for consistency with main package you should format same as main time package

**Comment by yaa110** [comment]
It has been changed in [v0.5.0](https://github.com/yaa110/go-persian-calendar/releases/tag/v0.5.0)
