### ISSUE TITLE
FirstDayOfMonth() method 

### ISSUE THREAD

**Issue by morilog** [yaa110/go-persian-calendar#13]
I think The `FirstDayOfMonth()` method must be returns the first day of month and reset the time to 00:00:00, but the method only reset the date and keeps original time

**Comment by yaa110** [comment]
Thank you for reporting the issue, for backward compatibility, `FirstMonthDay` method is not changed, rather, new methods of `BeginningOfWeek`, `BeginningOfMonth` and `BeginningOfYear` are added to [v0.5.0](https://github.com/yaa110/go-persian-calendar/releases/tag/v0.5.0).
