### ISSUE TITLE
Solutions to convert to other calendars

### ISSUE THREAD

**Issue by Hitaro** [yaa110/go-persian-calendar#2]
Hey bro, may you contribute in this topic: https://discourse.gohugo.io/t/9403/

Note: Hugo is the fastest static site generator.

**Comment by yaa110** [comment]
@Hitaro take a look at [Hoor](https://github.com/alireza-ahmadi/hoor)

**Comment by Hitaro** [comment]
Wow, just woW.

Thanks a lot.
