### ISSUE TITLE
t.nsec length 

### ISSUE THREAD

**Issue by alirezarabie** [yaa110/go-persian-calendar#23]
Hi Navid

strconv.Itoa(t.nsec) string length rarely goes less than 6 and because of you trying to get a string with lenght 6 of it run time error happening, the problematic code is :

"{ms}", "." + strconv.Itoa(t.nsec)[:6],

and the error is :
panic: runtime error: slice bounds out of range [:6] with length 5

I fixed it in my fork by adding "0" charcter as needed to end of it's string.

Good Luck.

**Comment by yaa110** [comment]
سلام، ممنون بابت گزارش باگ. در نسخه v1.1.3 فیکس شد

**Comment by alirezarabie** [comment]
I know my english is not good. Thank you for reminding me by typing persian. ;)
