### ISSUE TITLE
How to set Iran location when initiating `pt := ptime.Now()`

### ISSUE THREAD

**Issue by alipiry** [yaa110/go-persian-calendar#27]
Hi there,

Thanks for sharing this amazing useful library.

How can I set my now date location to `ptime.Iran()`:

```
pt := ptime.Now()
fmt.Println(pt.Location())

// output: Local
```

**Comment by alipiry** [comment]
@yaa110 🙌

**Comment by M03ED** [comment]
i have same question

**Comment by yaa110** [comment]
```go
pt := ptime.Now().In(ptime.Iran())
```

**Comment by M03ED** [comment]
> Please make sure that you are importing v1.2.0:
> 
> ```go
> pt := ptime.Now().In(ptime.Iran())
> ```

Thanks for new version

**Comment by sorushsaghari** [comment]
```go
ptime.Now().In(ptime.Iran())
```
i am doing the same thing but still the time is system time which is UTC

**Comment by alipiry** [comment]
> ```go
> ptime.Now().In(ptime.Iran())
> ```
> 
> i am doing the same thing but still the time is system time which is UTC

I managed to handle this problem using this:

```go

import (
	"time"
	_ "time/tzdata"

	ptime "github.com/yaa110/go-persian-calendar"
)

func Now() ptime.Time {
	n := time.Now().In(ptime.Iran())
	return ptime.New(n)
}


```

**Comment by yaa110** [comment]
@sorushsaghari what version are you using? check your go.mod and ensure that you are using the latest version.

**Comment by yaa110** [comment]
@alipiry in the latest version, `In` method is applied to a pointer of `ptime.Time` instead of returning a new instance of it.
