### ISSUE TITLE
Incorrect Date convertion from Gregorian to the Solar Hijri

### ISSUE THREAD

**Issue by seyedmmousavi** [yaa110/go-persian-calendar#28]
The last day of 1403 is 1403-12-30 which is equal to the 2025-03-20. Try to convert 2025-03-20 to the Solar Hijri by passing a `time.Time` object with 2025-03-20 value to the `ptime.New`. The result will be 1404-01-01.

**Comment by abtinokhovat** [comment]
[this](https://github.com/yaa110/go-persian-calendar/pull/31 ) does fix this issue
